### ISSUE TITLE
AUR is broken

### ISSUE THREAD

**Issue by norcalli** [brunelli/wl-clipboard-x11#2]
The AUR symlinks `xclip` and `xsel` to the wrong location:

`/home/$USER/.cache/yay/wl-clipboard-x11/pkg/wl-clipboard-x11/usr/share/wl-clipboard-x11/wl-clipboard-x11` instead of `/usr/share/wl-clipboard-x11/wl-clipboard-x11`

**Comment by brunelli** [comment]
Just pushed a fix to AUR and updated the package version. Thank you for the report!
