### ISSUE TITLE
Causing Sway to reload

### ISSUE THREAD

**Issue by samhh** [brunelli/wl-clipboard-x11#6]
For some reason this lib is causing my Sway instance to reload whenever anything is copied. This isn't happening with plain `xclip`. How can I go about debugging this?

**Comment by brunelli** [comment]
Could you give some more details?

Are you trying to copy something running `xclip` on a terminal? Do you have the same issue when copying with `wl-clipboard`?

**Comment by samhh** [comment]
Sorry for the poor issue detail, I've just spent a few minutes playing with this. The only reliable repro on my machine at the moment is with [pass](https://www.passwordstore.org/). It will reload Sway (or cause some sort of momentary schism akin to reloading) on copy (`pass dir/file -c`), and then again when the clipboard is cleared 45 seconds later. This doesn't happen with regular xclip installed.

**Comment by bugaevc** [comment]
> It will reload Sway (or cause some sort of momentary schism akin to reloading)

Oh, perhaps you mean the flashing present when using older versions of wl-clipboard (1.0) on Sway...

**Comment by brunelli** [comment]
@SamHH Could you install `wl-clipboard` from master (`wl-clipboard-git` if you're in Arch) and see if this fixes the issue?

**Comment by samhh** [comment]
That's fixed it! Thanks :smile: 

Is there a particular issue with wl-clipboard I can track in terms of a release?

**Comment by brunelli** [comment]
Yeap.

https://github.com/bugaevc/wl-clipboard/issues/35
